In [1]:
!pip install numpy

In [2]:
import numpy as np



In [3]:
print(np.__version__)

2.1.2


In [4]:
# 1. Creating arrays

In [5]:
list = [1,2,3]
print(list)

[1, 2, 3]


In [6]:
arr_list1 = np.array(list)
print(arr_list1)

[1 2 3]


In [7]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [8]:
list1 = [1,2,3]
list2 = [4,5,6] 
arr_list1_2 = np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [9]:
list1 = [1,2,3]
list2 = [4,5,6] 
list3 = [73,44,43]
arr_list1_3 = np.array([list1,list2,list3])
print(arr_list1_3)

[[ 1  2  3]
 [ 4  5  6]
 [73 44 43]]


In [10]:
# numpy array attributes
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [11]:
print("Shape",arr1.shape)
print("Size",arr1.size)
print("dType",arr1.dtype)
print("n_din",arr1.ndim)

Shape (2, 3)
Size 6
dType int64
n_din 2


In [12]:
# 3 Array initialization methods

In [13]:
# zeros array 
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# ones array 
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Full array

full_arr = np.full((3,2) , 7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [16]:
# Identity Matrix

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# empty array

print(np.empty(2))

[0. 0.]


In [18]:
# evenly spaced array
print(np.arange(1,10,2))

[1 3 5 7 9]


In [19]:
# specific  number of eqauliy (spaced) value between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [20]:
# random values array - float
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.0623767  0.66828693]
 [0.93130041 0.90997435]
 [0.28388587 0.73626802]]


In [21]:
# random values array - int
r_arrint = np.random.randint(1,100,(4,4))
print(r_arrint)

[[82 75 48 75]
 [66 65 30 51]
 [86 79  4 71]
 [44 65 94 83]]


In [22]:
# Array indexing and Slicing
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [23]:
print(a[0]) 

1


In [24]:
print(a[-1])

5


In [25]:
# Silcing :
# array[start:stop:step]   # stop - index that is not included in output

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [26]:
print(a[0:3])  #First 2 elements

[1 2 3]


In [27]:
print(a[-3:])  # Last 3 elements

[3 4 5]


In [28]:
print(a[1:4]) #Middle 3 elements

[2 3 4]


In [29]:
# 2D Array


In [30]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr2[1][2])

6


In [35]:
print(arr2[1])
print(arr2[1:])

[4 5 6]
[[4 5 6]]


In [36]:
print(arr2[:])

[[1 2 3]
 [4 5 6]]


In [37]:
print(arr2[:,0])

[1 4]


In [38]:
print(arr2[:,1])

[2 5]


In [39]:
print(arr2[:,2])

[3 6]


In [40]:
# 2D : [rows,colums]
# 3D : [layers/height,rows,columns]

In [44]:
arr3 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(arr3[:,0]) #1st col value
print(arr3[:,2]) #2nd col value

[3 6 9]


In [46]:
print(arr3[::2,0])

[1 7]


In [47]:
print(arr3[::,1:2])

[[2]
 [5]
 [8]]


In [48]:
# Array Reshaping and Flattening

In [51]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [55]:
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [57]:
reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [58]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [59]:
# Array Stacking and Splitting

In [62]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))  # row wise,Vertical stacking
print(np.hstack((a,b)))  # column wise, horizontal


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [63]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [68]:
split = (np.hsplit(c,3))

for s in split:
  print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [69]:
vsplit = (np.vsplit(c,2))

for s in vsplit:
  print(s)

[[1 2 3]]
[[4 5 6]]


In [70]:
# 7 Mathematical Operation on Array 

In [71]:
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [72]:
print(a+10)
print(a-10)
print(a*10)
print(a/10)

[ 20  30  50 -20]
[  0  10  30 -40]
[ 100  200  400 -300]
[ 1.  2.  4. -3.]


In [73]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [75]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [76]:
# 8 Mathematical Operations on Muliple Arrays

In [79]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [82]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [83]:
print(np.dot(a,b)) # dot product

32


In [84]:
print(a.T)  # Transpose

[1 2 3]


In [85]:
# Statistical Functions

In [86]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [87]:
print(np.sum(a))

21


In [89]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [ ]:
# 10 Array Compaison

In [90]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [92]:
print(a == b) # comparing each elements
print(np.array_equal(a,b)) # comparing complete array

[False False False]
False


In [93]:
# 11 Broadcasting

In [94]:
a = np.array([1,2,3,4,5])
b = np.array([5])
print(a+b)

[ 6  7  8  9 10]


In [99]:
c = np.array([[1,2,3],[3,4,2]])
d = np.array([10,20,30])
print(c+d)

[[11 22 33]
 [13 24 32]]


In [100]:
##  Handling with null value
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [101]:
print(np.isnan(data1))

[False False  True False False]


In [102]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [103]:
# save and load

In [104]:
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [ ]:
loaded_arr = np.lead('my_array.npy')